import './globals.css';
import styles from './layout.module.css';
import Profile from './components/Profile';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const name = 'Luigi';
export const siteTitle = 'Next.js Sample Website';

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div className={styles.container}>
          <nav className='flex'>
            <Link href='/' className='mr-5'>
              Home
            </Link>
            <Link href='/count'>Counter</Link>
          </nav>
          <Profile name={name}>{children}</Profile>
        </div>
      </body>
    </html>
  );
}
